ALTER TYPE "StepType" ADD VALUE 'ENTRY';

ALTER TABLE "RecipeStep" ADD COLUMN "entryUnit" TEXT;

ALTER TABLE "ProgressLog"
  ALTER COLUMN "quantity" TYPE DOUBLE PRECISION USING "quantity"::DOUBLE PRECISION;

ALTER TABLE "LogAudit"
  ALTER COLUMN "oldQuantity" TYPE DOUBLE PRECISION USING "oldQuantity"::DOUBLE PRECISION,
  ALTER COLUMN "newQuantity" TYPE DOUBLE PRECISION USING "newQuantity"::DOUBLE PRECISION;
