'use client'
import { useState } from 'react'
import ConfirmModal from '@/app/components/ConfirmModal'

type Worker = { id: string; name: string; role: string }
type Team = { id: string; name: string; members: { worker: Worker }[] }

export default function TeamManager({ initialTeams, workers }: { initialTeams: Team[]; workers: Worker[] }) {
  const [teams, setTeams] = useState(initialTeams); const [editing, setEditing] = useState<Team | null>(null)
  const [name, setName] = useState(''); const [workerIds, setWorkerIds] = useState<string[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<Team | null>(null)
  const open = (team?: Team) => { setEditing(team || ({ id: '', name: '', members: [] } as Team)); setName(team?.name || ''); setWorkerIds(team?.members.map(m => m.worker.id) || []); setError('') }
  const save = async () => { if (!editing || !name.trim()) return; setSaving(true); setError(''); try { const res = await fetch(editing.id ? `/api/teams/${editing.id}` : '/api/teams', { method: editing.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, workerIds }) }); const data = await res.json(); if (!res.ok) { setError(data.error || 'Unable to save team'); return } setTeams(editing.id ? teams.map(t => t.id === editing.id ? data.team : t).sort((a,b)=>a.name.localeCompare(b.name)) : [...teams, data.team].sort((a,b)=>a.name.localeCompare(b.name))); setEditing(null) } catch { setError('Connection error') } finally { setSaving(false) } }
  const remove = async () => { if (!deleting) return; const team = deleting; setDeleting(null); const res = await fetch(`/api/teams/${team.id}`, { method: 'DELETE' }); if (res.ok) setTeams(teams.filter(t => t.id !== team.id)); else setError('Unable to delete team') }
  return <div className="mt-5 space-y-3">
    <button className="bf-btn bf-btn-primary bf-btn-full" onClick={() => open()}>+ New Team</button>
    {error && <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}
    {teams.length === 0 ? <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No saved teams yet.</div> : teams.map(team => <button key={team.id} onClick={() => open(team)} className="w-full rounded-xl border border-border bg-card p-4 text-left"><span className="font-semibold text-foreground">{team.name}</span><span className="mt-1 block text-sm text-muted-foreground">{team.members.length ? team.members.map(m => m.worker.name).join(', ') : 'No members'}</span></button>)}
    {editing && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center" onClick={() => setEditing(null)}><div className="w-full max-w-md space-y-4 rounded-t-2xl border border-border bg-card p-5 sm:rounded-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{editing.id ? 'Edit Team' : 'New Team'}</h2><button className="bf-icon-btn" onClick={() => setEditing(null)}>×</button></div><input autoFocus className="w-full min-h-[48px] rounded-xl border border-border bg-background px-4" placeholder="Team name — e.g. Packaging" value={name} onChange={e=>setName(e.target.value.slice(0,60))}/><div><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Members</p><div className="max-h-[45vh] space-y-2 overflow-y-auto">{workers.map(worker => { const selected=workerIds.includes(worker.id); return <button key={worker.id} className={`bf-select-btn w-full justify-start ${selected?'bf-select-btn-active':''}`} onClick={()=>setWorkerIds(selected?workerIds.filter(id=>id!==worker.id):[...workerIds,worker.id])}>{selected?'✓ ':''}{worker.name}</button> })}</div></div><div className="flex gap-2"><button disabled={saving || !name.trim()} className="bf-btn bf-btn-primary flex-1" onClick={save}>{saving?'Saving…':'Save Team'}</button>{editing.id && <button className="bf-btn bf-btn-soft-danger" onClick={()=>setDeleting(editing)}>Delete</button>}</div></div></div>}
    <ConfirmModal open={!!deleting} title={`Delete ${deleting?.name || 'team'}?`} message="This removes the saved team only. Existing batch assignments stay unchanged." confirmLabel="Delete Team" confirmStyle="danger" onConfirm={remove} onCancel={()=>setDeleting(null)}/>
  </div>
}
